// A curated universe of frequently-discussed NSE stocks, used to detect which
// stocks an analyst is talking about in their feed text. Not exhaustive — it
// covers the Nifty 50 / Next 50 and popular mid-caps that research analysts
// actually name. To improve detection, add rows here (symbol must be the exact
// NSE symbol so `${symbol}.NS` resolves on Yahoo via /api/quote).
//
// `aliases` are the distinctive ways the company is written in prose (brand or
// short names). Keep them specific — avoid generic words that would false-match.

export interface Stock {
  symbol: string; // exact NSE symbol
  name: string; // display name
  aliases?: string[];
}

export const STOCK_UNIVERSE: Stock[] = [
  // ---- Nifty 50 core ----
  { symbol: "RELIANCE", name: "Reliance Industries", aliases: ["Reliance"] },
  { symbol: "TCS", name: "Tata Consultancy Services" },
  { symbol: "HDFCBANK", name: "HDFC Bank" },
  { symbol: "ICICIBANK", name: "ICICI Bank" },
  { symbol: "INFY", name: "Infosys" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel", aliases: ["Airtel"] },
  { symbol: "ITC", name: "ITC" },
  { symbol: "SBIN", name: "State Bank of India", aliases: ["SBI"] },
  { symbol: "LT", name: "Larsen & Toubro", aliases: ["L&T"] },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever", aliases: ["HUL"] },
  { symbol: "BAJFINANCE", name: "Bajaj Finance" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", aliases: ["Kotak Bank", "Kotak Mahindra"] },
  { symbol: "HCLTECH", name: "HCL Technologies", aliases: ["HCL Tech"] },
  { symbol: "AXISBANK", name: "Axis Bank" },
  { symbol: "MARUTI", name: "Maruti Suzuki", aliases: ["Maruti"] },
  { symbol: "SUNPHARMA", name: "Sun Pharma" },
  { symbol: "ASIANPAINT", name: "Asian Paints" },
  { symbol: "TITAN", name: "Titan Company", aliases: ["Titan"] },
  { symbol: "NTPC", name: "NTPC" },
  { symbol: "ONGC", name: "ONGC" },
  { symbol: "ADANIENT", name: "Adani Enterprises" },
  { symbol: "ADANIPORTS", name: "Adani Ports" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement", aliases: ["UltraTech"] },
  { symbol: "POWERGRID", name: "Power Grid", aliases: ["Powergrid"] },
  { symbol: "TATAMOTORS", name: "Tata Motors" },
  { symbol: "WIPRO", name: "Wipro" },
  { symbol: "M&M", name: "Mahindra & Mahindra", aliases: ["M&M"] },
  { symbol: "JSWSTEEL", name: "JSW Steel" },
  { symbol: "COALINDIA", name: "Coal India" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv" },
  { symbol: "NESTLEIND", name: "Nestle India", aliases: ["Nestle"] },
  { symbol: "TATASTEEL", name: "Tata Steel" },
  { symbol: "TECHM", name: "Tech Mahindra" },
  { symbol: "HDFCLIFE", name: "HDFC Life" },
  { symbol: "GRASIM", name: "Grasim" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank", aliases: ["IndusInd"] },
  { symbol: "SBILIFE", name: "SBI Life" },
  { symbol: "DRREDDY", name: "Dr Reddy's Laboratories", aliases: ["Dr Reddy", "Dr Reddys"] },
  { symbol: "CIPLA", name: "Cipla" },
  { symbol: "EICHERMOT", name: "Eicher Motors", aliases: ["Eicher"] },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto" },
  { symbol: "BRITANNIA", name: "Britannia" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp", aliases: ["Hero Moto"] },
  { symbol: "DIVISLAB", name: "Divi's Laboratories", aliases: ["Divis Labs", "Divi's Labs", "Divis"] },
  { symbol: "TATACONSUM", name: "Tata Consumer Products", aliases: ["Tata Consumer"] },
  { symbol: "HINDALCO", name: "Hindalco" },
  { symbol: "BPCL", name: "BPCL" },
  { symbol: "LTIM", name: "LTIMindtree", aliases: ["LTI Mindtree", "Mindtree"] },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance" },
  { symbol: "TRENT", name: "Trent" },
  { symbol: "JIOFIN", name: "Jio Financial Services", aliases: ["Jio Financial", "JioFin"] },
  // ---- Next 50 / large caps ----
  { symbol: "ADANIGREEN", name: "Adani Green Energy", aliases: ["Adani Green"] },
  { symbol: "ADANIPOWER", name: "Adani Power" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements", aliases: ["Ambuja"] },
  { symbol: "DLF", name: "DLF" },
  { symbol: "BANKBARODA", name: "Bank of Baroda", aliases: ["BoB"] },
  { symbol: "PNB", name: "Punjab National Bank" },
  { symbol: "IOC", name: "Indian Oil", aliases: ["Indian Oil Corporation"] },
  { symbol: "GAIL", name: "GAIL" },
  { symbol: "VEDL", name: "Vedanta" },
  { symbol: "ETERNAL", name: "Eternal (Zomato)", aliases: ["Zomato", "Eternal"] },
  { symbol: "DMART", name: "Avenue Supermarts", aliases: ["DMart", "D-Mart"] },
  { symbol: "PIDILITIND", name: "Pidilite Industries", aliases: ["Pidilite"] },
  { symbol: "SIEMENS", name: "Siemens" },
  { symbol: "ABB", name: "ABB India" },
  { symbol: "HAL", name: "Hindustan Aeronautics" },
  { symbol: "BEL", name: "Bharat Electronics" },
  { symbol: "IRCTC", name: "IRCTC" },
  { symbol: "IRFC", name: "IRFC" },
  { symbol: "PFC", name: "Power Finance Corporation" },
  { symbol: "RECLTD", name: "REC" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment", aliases: ["Cholamandalam", "Chola Finance"] },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life", aliases: ["ICICI Pru Life", "ICICI Prudential"] },
  { symbol: "ICICIGI", name: "ICICI Lombard" },
  { symbol: "SBICARD", name: "SBI Cards" },
  { symbol: "TVSMOTOR", name: "TVS Motor", aliases: ["TVS Motors"] },
  { symbol: "GODREJCP", name: "Godrej Consumer", aliases: ["Godrej Consumer Products"] },
  { symbol: "DABUR", name: "Dabur" },
  { symbol: "MARICO", name: "Marico" },
  { symbol: "COLPAL", name: "Colgate-Palmolive", aliases: ["Colgate"] },
  { symbol: "BERGEPAINT", name: "Berger Paints", aliases: ["Berger"] },
  { symbol: "HAVELLS", name: "Havells" },
  { symbol: "VBL", name: "Varun Beverages" },
  { symbol: "UNITDSPR", name: "United Spirits", aliases: ["McDowell"] },
  { symbol: "TATAPOWER", name: "Tata Power" },
  { symbol: "NHPC", name: "NHPC" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power", aliases: ["Jindal Steel", "JSPL"] },
  { symbol: "SAIL", name: "SAIL" },
  { symbol: "NMDC", name: "NMDC" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson", aliases: ["Motherson"] },
  { symbol: "BOSCHLTD", name: "Bosch" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland" },
  { symbol: "MRF", name: "MRF" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries", aliases: ["Balkrishna", "BKT Tyres"] },
  { symbol: "LICI", name: "Life Insurance Corporation", aliases: ["LIC"] },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance", aliases: ["Muthoot"] },
  { symbol: "INDIGO", name: "InterGlobe Aviation", aliases: ["IndiGo"] },
  { symbol: "NAUKRI", name: "Info Edge", aliases: ["Naukri"] },
  { symbol: "PAYTM", name: "Paytm", aliases: ["One97"] },
  { symbol: "POLICYBZR", name: "PB Fintech", aliases: ["Policybazaar"] },
  { symbol: "NYKAA", name: "Nykaa", aliases: ["FSN E-Commerce"] },
  { symbol: "LODHA", name: "Lodha", aliases: ["Macrotech"] },
  { symbol: "GODREJPROP", name: "Godrej Properties" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty" },
  { symbol: "PRESTIGE", name: "Prestige Estates" },
  { symbol: "PHOENIXLTD", name: "Phoenix Mills" },
  { symbol: "INDHOTEL", name: "Indian Hotels", aliases: ["Taj Hotels"] },
  { symbol: "JUBLFOOD", name: "Jubilant FoodWorks", aliases: ["Jubilant Food", "Dominos", "Domino's"] },
  // ---- IT / new-age / capital markets ----
  { symbol: "PERSISTENT", name: "Persistent Systems", aliases: ["Persistent"] },
  { symbol: "COFORGE", name: "Coforge" },
  { symbol: "MPHASIS", name: "Mphasis" },
  { symbol: "TATAELXSI", name: "Tata Elxsi" },
  { symbol: "POLYCAB", name: "Polycab" },
  { symbol: "DIXON", name: "Dixon Technologies", aliases: ["Dixon"] },
  { symbol: "KPITTECH", name: "KPIT Technologies", aliases: ["KPIT"] },
  { symbol: "CGPOWER", name: "CG Power" },
  { symbol: "SUZLON", name: "Suzlon Energy", aliases: ["Suzlon"] },
  { symbol: "BSE", name: "BSE" },
  { symbol: "CDSL", name: "CDSL" },
  { symbol: "ANGELONE", name: "Angel One" },
  { symbol: "IEX", name: "Indian Energy Exchange" },
  { symbol: "SWIGGY", name: "Swiggy" },
  { symbol: "OLAELEC", name: "Ola Electric" },
  // ---- Banks / NBFCs ----
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank", aliases: ["IDFC First"] },
  { symbol: "FEDERALBNK", name: "Federal Bank" },
  { symbol: "AUBANK", name: "AU Small Finance Bank", aliases: ["AU Bank", "AU Small Finance"] },
  { symbol: "BANDHANBNK", name: "Bandhan Bank" },
  { symbol: "YESBANK", name: "Yes Bank" },
  { symbol: "LTF", name: "L&T Finance" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance", aliases: ["Manappuram"] },
  { symbol: "BAJAJHFL", name: "Bajaj Housing Finance", aliases: ["Bajaj Housing"] },
  // ---- Pharma / healthcare ----
  { symbol: "LUPIN", name: "Lupin" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma", aliases: ["Aurobindo"] },
  { symbol: "TORNTPHARM", name: "Torrent Pharma" },
  { symbol: "ALKEM", name: "Alkem Laboratories", aliases: ["Alkem"] },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences", aliases: ["Zydus"] },
  { symbol: "BIOCON", name: "Biocon" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals", aliases: ["Glenmark"] },
  { symbol: "LAURUSLABS", name: "Laurus Labs", aliases: ["Laurus"] },
  { symbol: "MANKIND", name: "Mankind Pharma" },
  { symbol: "MAXHEALTH", name: "Max Healthcare" },
  { symbol: "FORTIS", name: "Fortis Healthcare", aliases: ["Fortis"] },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare", aliases: ["Metropolis"] },
  { symbol: "LALPATHLAB", name: "Dr Lal PathLabs", aliases: ["Lal PathLabs"] },
  // ---- Chemicals / others ----
  { symbol: "PIIND", name: "PI Industries" },
  { symbol: "SRF", name: "SRF" },
  { symbol: "UPL", name: "UPL" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite" },
  { symbol: "AARTIIND", name: "Aarti Industries", aliases: ["Aarti"] },
  { symbol: "TATACHEM", name: "Tata Chemicals" },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion", aliases: ["ABFRL"] },
  { symbol: "PAGEIND", name: "Page Industries", aliases: ["Jockey"] },
];
